image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/buildpack-deps:stable

include:
  - local: workflows/benchmark.yml
    rules:
      - if: '$WORKFLOW == "benchmark"'
  - local: workflows/create-cache.yml
    rules:
      - if: '$WORKFLOW == "create-cache"'

test:
  when: on_failure
  script:
    - ./info.sh
