version: 2.1
parameters:
  workflow:
    type: string
    default: ""

jobs:
  ssh:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
      - checkout
  benchmark:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run:
          command: export PATH="$(pwd)/scripts:${PATH}" && sudo -E benchmark.sh
          no_output_timeout: 45m

workflows:
  ssh-workflow:
    when:
      equal: [ssh, << pipeline.parameters.workflow >> ]
    jobs:
      - ssh
  benchmark-workflow:
    when:
      equal: [benchmark, << pipeline.parameters.workflow >> ]
    jobs:
      - benchmark
