version: 2.1
parameters:
  workflow:
    type: string
    default: ""

jobs:
  ssh:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
      - checkout
  benchmark:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: arm.large
    steps:
      - checkout
      - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.12/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - run:
          command: earthly --ci +benchmark
          no_output_timeout: 45m

workflows:
  ssh-workflow:
    when:
      equal: [ssh, << pipeline.parameters.workflow >> ]
    jobs:
      - ssh
  benchmark-workflow:
    when:
      equal: [benchmark, << pipeline.parameters.workflow >> ]
    jobs:
      - benchmark
