version: 2.1
parameters:
  workflow:
    type: string
    default: ""

jobs:
  ssh:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run: apt-get -qqy update && sudo apt-get install -qqy mosh
  benchmark:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run:
          command: sudo -E env PATH="$(pwd)/scripts:${PATH}" benchmark.sh
          no_output_timeout: 45m

workflows:
  ssh-workflow:
    when:
      or:
        - equal: [ssh, << pipeline.parameters.workflow >> ]
        - equal: [main, << pipeline.git.branch >> ]
    jobs:
      - ssh
  benchmark-workflow:
    when:
      equal: [benchmark, << pipeline.parameters.workflow >> ]
    jobs:
      - benchmark
