version: 2.1
parameters:
  workflow:
    type: string
    default: ""

jobs:
  ssh:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
      - checkout
  benchmark:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: arm.large
    steps:
      - checkout
      - run:
          command: docker build -f Dockerfile.benchmark -t benchmark:latest --build-arg="DATE='$(date)'" .
          no_output_timeout: 45m

workflows:
  ssh-workflow:
    when:
      equal: [ssh, << pipeline.parameters.workflow >> ]
    jobs:
      - ssh
  benchmark-workflow:
    when:
      equal: [benchmark, << pipeline.parameters.workflow >> ]
    jobs:
      - benchmark
