version: 2.1
parameters:
  workflow:
    type: string
    default: "hello"

jobs:
  ssh:
    machine:
      image: ubuntu-2204:current
    working_directory: /dev/shm
    resource_class: arm.medium
    steps:
      - checkout:
          path: /dev/shm/esperoj

workflows:
  ssh-workflow:
    when:
      equal: [ssh, << pipeline.parameters.workflow >> ]
    jobs:
      - ssh
