name: Benchmark
run-name: Benchmark
on: [workflow_dispatch]
jobs:
  Benchmark:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./info.sh
      - run: ./setup.sh
      - run: ./speedtest.sh
      - run: ./benchmark.sh
