name: Benchmark
run-name: Benchmark
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Benchmark
        run: sudo env PATH="$(pwd)/scripts:${PATH}" benchmark.sh && ./scripts/network-speed.sh -r na
