name: Benchmark
run-name: Benchmark
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:stable
    timeout-minutes: 60
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./scripts/info.sh
      - run: ./scripts/setup.sh
      - run: cd scripts && ./speedtest.sh
      - run: ./scripts/benchmark.sh
