name: Benchmark
run-name: Benchmark
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    container: buildpack-deps:stable
      image: 
    timeout-minutes: 60
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Benchmark
        run: env PATH="$(pwd)/scripts:${PATH}" ./scripts/benchmark.sh
