name: SSH
on: workflow_dispatch
jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_REGION: jp
